name: Upstream Sync

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - .github/**
  workflow_run:
    workflows: ["Upstream Sync"]  # 监听 Upstream Sync 工作流
    types:
      - completed  # 仅在工作流完成时触发
  workflow_dispatch:


jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@main

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@main
        with:
          upstream_sync_repo: danny-avila/LibreChat
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "::error::由于权限不足，导致同步失败（这是预期的行为），请前往仓库首页手动执行[Sync fork]。"
          echo "::error::Due to insufficient permissions, synchronization failed (as expected). Please go to the repository homepage and manually perform [Sync fork]."
          exit 1